"use client";

import { Providers } from "@/redux/providers";
import "../styles/global.scss";
import { FullStoryScript } from "@/components/scripts/FullStoryScript";
import AuthCheck from "@/features/hoc/AuthCheck";
import { AnalyticsScript } from "@/components/scripts/AnalyticsScript";
import ErrorBoundary from "./error-boundary";
import { useEffect } from "react";

// export async function generateMetadata({ params }) {
//   let title = "Bind AI Copilot";
//   let description =
//     "Get exclusive access to top generative AI models like GPT-4o, Claude-3 Opus, Mistral, and more with Bind AI Copilot. Alternative to ChatGPT, Microsoft Bing Copilot, Perplexity AI.";

//   return {
//     title,
//     description,
//   };
// }

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  useEffect(() => {
    if (typeof window !== 'undefined') {
      // Check if the screen width is greater than or equal to 1024px (typical desktop size)
      if (window.innerWidth > 1024) {
        // Inject Crisp script for desktop only
        window.$crisp = [];
        window.CRISP_WEBSITE_ID = "ac0c01c3-181d-4998-80b6-88b3eadf7759";
        (function () {
          const d = document;
          const s = d.createElement("script");
          s.src = "https://client.crisp.chat/l.js";
          s.async = 1;
          d.getElementsByTagName("head")[0].appendChild(s);
        })();
      }
    }
  }, []);
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.svg" />
        <FullStoryScript />
        <AnalyticsScript />
      </head>
      <body>
        <Providers>
          <ErrorBoundary>
            <AuthCheck>{children}</AuthCheck>
          </ErrorBoundary>
        </Providers>
      </body>
    </html>
  );
}
