export const ModelCategory = [
  {
    id: 1,
    label: "All",
    value: "all",
  },
  {
    id: 2,
    label: "Advanced Models",
    value: "advanced_models",
    botList: [
       // {
      //   id: 8,
      //   label: "Gemini Pro 1.5 (latest)",
      //   value: "claude-3.5-haiku",
      //   description:
      //     "Gemini Pro 1.5 is Google AI's most advanced language model, outperforming previous models like Gemini Pro and Claude 3.5 in various benchmarks.",
      //   contextWindow: "1M",
      //   inputPricing: "$1.25",
      //   outputPricing: "$5.00",
      //   icon: "google-gemini-icon",
      //   type: "premium",
      // },
      {
        id: 0,
        label: "Claude 3.5 Haiku",
        value: "claude-3.5-haiku",
        description:
          "Claude 3.5 Haiku is a fast and efficient AI model, excelling in code generation, reasoning, and content creation.",
        contextWindow: "200k",
        inputPricing: "$1.00",
        outputPricing: "$5.00",
        icon: "claude",
        type: "premium",
      },
      {
        id: 1,
        label: "GPT-4o",
        value: "gpt-4-omni",
        description:
          "OpenAI's new AI model that understands multiple forms of input (text, voice, video) for a more natural interaction",
        contextWindow: "100K",
        inputPricing: "$10.00",
        outputPricing: "$30.00",
        icon: "gpt",
        type: "premium",
      },
      {
        id: 2,
        label: "GPT-4o mini",
        value: "gpt-4o-mini",
        description:
          "GPT-4o mini, advancing cost-efficient intelligence, is the latest model from OpenAI. Designed for faster responses and lower cost",
        contextWindow: "128K ",
        inputPricing: "$0.150 ",
        outputPricing: "$0.600 ",
        icon: "openai_mini",
        svg: true,
        type: "premium",
      },
      // {
      //   id: 1,
      //   label: "OpenAI o1",
      //   value: "o1-mini",
      //   description:
      //     "GPT o1 mini is the most advanced model by OpenAI, which outperforms it's predecessor.",
      //   contextWindow: "128K",
      //   inputPricing: "$3.00",
      //   outputPricing: "$12.00",
      //   icon: "openai_o1",
      //   svg: true,
      //   type: "premium",
      // },
      {
        id: 3,
        label: "Claude 3.5 Sonnet",
        value: "claude-3.5-sonnet",
        description:
          "Claude 3.5 Sonnet outperforms GPT-4o and Claude 3 Opus in Code Generation and Reasoning",
        contextWindow: "200k",
        inputPricing: "$3.00",
        outputPricing: "$15.00",
        icon: "claude",
        type: "premium",
      },
      // {
      //   id: 1,
      //   label: "Claude 3 Opus",
      //   value: "claude-3-opus",
      //   description:
      //     "Claude's most intelligent model, outperforms its peers on most of the common evaluation benchmarks.",
      //   contextWindow: "200K",
      //   inputPricing: "$15.00",
      //   outputPricing: "$75.00",
      //   icon: "claude",
      //   type: "premium",
      // },
      // {
      //   id: 2,
      //   label: "GPT 4 Turbo",
      //   value: "gpt-4-turbo",
      //   description: "Open AI's most intelligent model for language tasks.",
      //   contextWindow: "128K",
      //   inputPricing: "$10.00",
      //   outputPricing: "$30.00",
      //   icon: "gpt",
      //   type: "premium",
      // },
      {
        id: 5,
        label: "Codestral Latest",
        value: "codestral-latest",
        description:
          "State-of-the-art Mistral model trained specifically for code tasks",
        contextWindow: "32K",
        inputPricing: "$1.00",
        outputPricing: "$3.00",
        icon: "mistral-ai",
        type: "premium",
      },
      {
        id: 6,
        label: "mistral-large",
        value: "mistral-large-latest",
        description:
          "Top-tier reasoning for high-complexity tasks. The most powerful model of the Mistral AI family.",
        contextWindow: "32K",
        inputPricing: "$8.00",
        outputPricing: "$24.00",
        icon: "mistral-ai",
        type: "premium",
      },
      {
        id: 7,
        label: "Open Mixtral 8x22b",
        value: "open-mixtral-8x22b",
        description:
          "Mixtral 8x22B is currently the most performant open model. A 22B sparse Mixture-of-Experts (SMoE). Uses only 39B active parameters out of 141B.",
        contextWindow: "64K",
        inputPricing: "$2.00",
        outputPricing: "$6.00",
        icon: "mistral-ai",
        type: "premium",
      },
    ],
  },
  {
    id: 3,
    label: "Fast General Purpose",
    value: "general_purpose",
    botList: [
      {
        id: 1,
        label: "Command R",
        value: "command-r",
        description:
          "Great for simpler retrieval augmented generation (RAG) and single-step tool use tasks.",
        contextWindow: "128K",
        inputPricing: "$0.50",
        outputPricing: "$1.50",
        icon: "cohere",
        type: "free",
      },
      {
        id: 2,
        label: "GPT 3.5 Turbo",
        value: "gpt-3.5-turbo",
        description: "OpenAI's flagship model for language tasks.",
        contextWindow: "16K",
        inputPricing: "$0.50",
        outputPricing: "$1.50",
        icon: "gpt",
        type: "free",
      },
      {
        id: 3,
        label: "Claude 3 Haiku",
        value: "claude-3-haiku",
        description: "Near-instant response time with Claude.",
        contextWindow: "200k",
        inputPricing: "$0.25",
        outputPricing: "$1.25",
        icon: "claude",
        type: "free",
      },
      {
        id: 4,
        label: "Llama 3 8B",
        value: "groq-llama-3-8b-8k",
        description:
          "Powerful and efficient llm by Meta AI, ideal for various tasks. Offers fast and cost-effective performance on Groq's LPU hardware.",
        contextWindow: "8k",
        inputPricing: "$0.05",
        outputPricing: "$0.10",
        icon: "claude",
        type: "free",
      },
      {
        id: 5,
        label: "Llama 3 70B",
        value: "groq-llama-3-70b-8k",
        description:
          "Highly powerful llm by Meta AI, ideal for complex tasks and potentially higher accuracy. Efficient performance on Groq's LPU hardware.",
        contextWindow: "8k",
        inputPricing: "$0.59",
        outputPricing: "$0.79",
        icon: "claude",
        type: "free",
      },
      {
        id: 6,
        label: "GROQ Mixtral 8x7B 32K IT",
        value: "groq-mixtral-8x7b-32k-it",
        description: "Near-instant response time with GROQ Mixtral.",
        contextWindow: "32k",
        inputPricing: "$0.27",
        outputPricing: "$0.27",
        icon: "groq-logo",
        svg: true,
        type: "free",
      },
      {
        id: 7,
        label: "GROQ Gemma 7B IT",
        value: "groq-gemma-7b-it",
        description:
          "The GROQ Gemma 7B IT is a next-generation model designed to eliminate IT complexity and empower businesses with actionable insights.",
        contextWindow: "8k",
        inputPricing: "$0.10",
        outputPricing: "$0.10",
        icon: "groq-logo",
        svg: true,
        type: "free",
      },
    ],
  },
  {
    id: 4,
    label: "Long Context Window",
    value: "context_window",
    botList: [
      {
        id: 1,
        label: "Command R+",
        value: "command-r-plus",
        description:
          "Optimized for conversational interaction and long-context tasks",
        contextWindow: "128k",
        inputPricing: "$3.00",
        outputPricing: "$15.00",
        icon: "cohere",
        type: "premium",
      },
      {
        id: 2,
        label: "Claude 3 Sonnet",
        value: "claude-3-sonnet",
        description:
          "Sonnet strikes the ideal balance between intelligence and speed.",
        contextWindow: "200k",
        inputPricing: "$3.00",
        outputPricing: "$15.00",
        icon: "claude",
        type: "premium",
      },
    ],
  },
  // {
  //   id: 5,
  //   label: "Image Generation Models",
  //   value: "image_generation",
  // },
];